### ISSUE TITLE
uxmd.io Does not render

### ISSUE THREAD

**Issue by build3r** [lobau/uxmd#5]
The webapp does not render the console show the below error. Tried on Chrome and Firefox.
```
script.js:19 Uncaught TypeError: marked is not a function
    at render (script.js:19)
    at window.onload (script.js:92)
```
The issue seems to be on this [line](https://github.com/lobau/uxmd/blob/11eb489a418c17147ce564951a5f94e0b150a00e/public/script.js#L19)
Sample link
[https://www.uxmd.io/8vcTIcty9oyZVUtZgNLClZNS](https://www.uxmd.io/8vcTIcty9oyZVUtZgNLClZNS)

**Comment by lobau** [comment]
Thanks a lot for the report.
Yeah, I noticed that yesterday. For whatever reason, the markdown library I'm using broke something.
If you know what's going on, please open a PR, otherwise I will try to look at it later.

**Comment by gee-forr** [comment]
Hope it gets fixed soon, I really enjoyed using UXMD before it broke

**Comment by lobau** [comment]
Haha yes sorry I was super busy these past few weeks. I will work on that this week now that I have some time for thanksgiving :)

**Comment by lobau** [comment]
Ok this should be fixed now :)

**Comment by gee-forr** [comment]
Amazing!!! Thank you so much!!!
